
export const ROLES = {
    ADMIN: 'admin',
    QA_TESTER: 'qa_tester',
    REQUESTER: 'requester',
    DEVELOPER: 'developer',
    MANAGER: 'manager',
    HR_ADMIN: 'hr_admin',
    PROJECT_MANAGER: 'project_manager',
    SENIOR_QA: 'senior_qa',
} as const;

export const ALL_PERMISSIONS = {
    // Admin Section
    ADMIN_SECTION: {
        READ: 'admin:read',
    },
    USERS: {
        CREATE: 'users:create',
        READ: 'users:read',
        UPDATE: 'users:update',
        DELETE: 'users:delete',
    },
    ROLES: {
        MANAGE: 'roles:manage',
    },
    TEAMS: {
        CREATE: 'teams:create',
        READ: 'teams:read',
        UPDATE: 'teams:update',
        DELETE: 'teams:delete',
    },
    PROJECTS: {
        CREATE: 'projects:create',
        READ: 'projects:read',
        UPDATE: 'projects:update',
        DELETE: 'projects:delete',
        ASSIGN_TASKS: 'projects:assign_tasks',
    },
    PROJECT_INSIGHTS: {
        READ: 'insights:read',
    },
    PROJECT_DIAGNOSTICS: {
        RUN: 'diagnostics:run',
    },
    PAYROLL: {
        READ: 'payroll:read',
    },
    LEAVE_MANAGEMENT: {
        MANAGE: 'leave:manage',
    },
    INFRACTIONS: {
        MANAGE: 'infractions:manage',
    },
    BONUSES: {
        MANAGE: 'bonuses:manage',
    },
    
    // QA & Requester Section
    REQUESTS: {
        CREATE: 'requests:create',
        READ_ALL: 'requests:read_all',
        READ_OWN: 'requests:read_own',
        APPROVE: 'requests:approve',
        REJECT: 'requests:reject',
        ADD_COMMENT: 'requests:add_comment',
        RATE_SUBMISSION: 'requests:rate_submission',
        GIVE_FEEDBACK: 'requests:give_feedback',
    },
    CERTIFICATES: {
        READ: 'certificates:read',
        REVOKE: 'certificates:revoke',
    },
    LEADERBOARDS: {
        READ: 'leaderboards:read',
    },
    RECORDS: {
        READ_OWN: 'records:read_own',
    },
    LEAVE: {
        REQUEST: 'leave:request',
    },
    DESIGNS: {
        CREATE: 'designs:create',
        READ_OWN: 'designs:read_own',
        READ_ALL: 'designs:read_all',
        APPROVE: 'designs:approve',
    }
} as const;


const ADMIN_PERMISSIONS = [
    ALL_PERMISSIONS.ADMIN_SECTION.READ,
    ALL_PERMISSIONS.USERS.CREATE,
    ALL_PERMISSIONS.USERS.READ,
    ALL_PERMISSIONS.USERS.UPDATE,
    ALL_PERMISSIONS.USERS.DELETE,
    ALL_PERMISSIONS.ROLES.MANAGE,
    ALL_PERMISSIONS.TEAMS.CREATE,
    ALL_PERMISSIONS.TEAMS.READ,
    ALL_PERMISSIONS.TEAMS.UPDATE,
    ALL_PERMISSIONS.TEAMS.DELETE,
    ALL_PERMISSIONS.PROJECTS.CREATE,
    ALL_PERMISSIONS.PROJECTS.READ,
    ALL_PERMISSIONS.PROJECTS.UPDATE,
    ALL_PERMISSIONS.PROJECTS.DELETE,
    ALL_PERMISSIONS.PROJECTS.ASSIGN_TASKS,
    ALL_PERMISSIONS.PROJECT_INSIGHTS.READ,
    ALL_PERMISSIONS.PROJECT_DIAGNOSTICS.RUN,
    ALL_PERMISSIONS.PAYROLL.READ,
    ALL_PERMISSIONS.LEAVE_MANAGEMENT.MANAGE,
    ALL_PERMISSIONS.INFRACTIONS.MANAGE,
    ALL_PERMISSIONS.BONUSES.MANAGE,
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.CERTIFICATES.REVOKE,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.DESIGNS.READ_ALL,
    ALL_PERMISSIONS.DESIGNS.APPROVE,
];

const QA_TESTER_PERMISSIONS = [
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.REQUESTS.APPROVE,
    ALL_PERMISSIONS.REQUESTS.REJECT,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.REQUESTS.RATE_SUBMISSION,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.CERTIFICATES.REVOKE,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.READ_ALL, // Can view designs
];

const REQUESTER_PERMISSIONS = [
    ALL_PERMISSIONS.REQUESTS.CREATE,
    ALL_PERMISSIONS.REQUESTS.READ_OWN,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.REQUESTS.GIVE_FEEDBACK,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.CREATE,
    ALL_PERMISSIONS.DESIGNS.READ_OWN,
];

const DEVELOPER_PERMISSIONS = [
    ALL_PERMISSIONS.PROJECTS.READ,
    ALL_PERMISSIONS.PROJECTS.UPDATE,
    ALL_PERMISSIONS.REQUESTS.CREATE,
    ALL_PERMISSIONS.REQUESTS.READ_OWN,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.CREATE,
    ALL_PERMISSIONS.DESIGNS.READ_OWN,
];

const MANAGER_PERMISSIONS = [
    ALL_PERMISSIONS.TEAMS.READ,
    ALL_PERMISSIONS.PROJECTS.READ,
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.READ_ALL,
];

const HR_ADMIN_PERMISSIONS = [
    ALL_PERMISSIONS.USERS.READ,
    ALL_PERMISSIONS.USERS.UPDATE,
    ALL_PERMISSIONS.PAYROLL.READ,
    ALL_PERMISSIONS.LEAVE_MANAGEMENT.MANAGE,
    ALL_PERMISSIONS.INFRACTIONS.MANAGE,
    ALL_PERMISSIONS.BONUSES.MANAGE,
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
];

const PROJECT_MANAGER_PERMISSIONS = [
    ALL_PERMISSIONS.PROJECTS.CREATE,
    ALL_PERMISSIONS.PROJECTS.READ,
    ALL_PERMISSIONS.PROJECTS.UPDATE,
    ALL_PERMISSIONS.PROJECTS.ASSIGN_TASKS,
    ALL_PERMISSIONS.PROJECT_INSIGHTS.READ,
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.READ_ALL,
];

const SENIOR_QA_PERMISSIONS = [
    ALL_PERMISSIONS.REQUESTS.READ_ALL,
    ALL_PERMISSIONS.REQUESTS.APPROVE,
    ALL_PERMISSIONS.REQUESTS.REJECT,
    ALL_PERMISSIONS.REQUESTS.ADD_COMMENT,
    ALL_PERMISSIONS.REQUESTS.RATE_SUBMISSION,
    ALL_PERMISSIONS.CERTIFICATES.READ,
    ALL_PERMISSIONS.CERTIFICATES.REVOKE,
    ALL_PERMISSIONS.LEADERBOARDS.READ,
    ALL_PERMISSIONS.RECORDS.READ_OWN,
    ALL_PERMISSIONS.LEAVE.REQUEST,
    ALL_PERMISSIONS.DESIGNS.READ_ALL,
    ALL_PERMISSIONS.DESIGNS.APPROVE,
];

export const PERMISSIONS_BY_ROLE = {
    [ROLES.ADMIN]: ADMIN_PERMISSIONS,
    [ROLES.QA_TESTER]: QA_TESTER_PERMISSIONS,
    [ROLES.REQUESTER]: REQUESTER_PERMISSIONS,
    [ROLES.DEVELOPER]: DEVELOPER_PERMISSIONS,
    [ROLES.MANAGER]: MANAGER_PERMISSIONS,
    [ROLES.HR_ADMIN]: HR_ADMIN_PERMISSIONS,
    [ROLES.PROJECT_MANAGER]: PROJECT_MANAGER_PERMISSIONS,
    [ROLES.SENIOR_QA]: SENIOR_QA_PERMISSIONS,
};
